---
title: "Cade Sandbox"
author: "Cade Lau, cadelau@umich.edu"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# do k fold cross validation
```{r}
library(C50)
library(gmodels)
library(partykit)
library(caret)
set.seed(123)

shop <- read.csv("online_shoppers_intention.csv")

shop$Month <- NULL
shop$OperatingSystems <- NULL
shop$Browser <- NULL
shop$Region <- NULL
shop$TrafficType <- NULL
shop$PageValues <- NULL

shop$Weekend <- ifelse(shop$Weekend == TRUE, 1, 0)
shop$Revenue <- ifelse(shop$Revenue == TRUE, 1, 0)

index = which(colnames(shop) == "Revenue")

shop_mm <- as.data.frame(model.matrix(~. - 1, data = shop[,-index]))
shop_mm$Revenue <- shop$Revenue

str(shop_mm)
normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}

summary(shop$PageValues)

shop_norm <- as.data.frame(lapply(shop_mm[,-index], normalize))
summary(shop_norm)

log_mod <- glm(Revenue ~ ., data = shop_norm, family = binomial(link = "logit"))
summary(log_mod)

shop_norm$Revenue <- as.factor(shop_norm$Revenue)

rows <- sample(nrow(shop_norm))
shop_new <- shop_norm[rows,]

shop_train <- shop_new[1:8630,]
shop_test <- shop_new[8631:12330,]
```

# 10-Fold CV for Decision Tree

```{r}
index = which(colnames(shop_train)=="Revenue")
folds = createFolds(shop_train$Revenue, 10)

dt_cv1 = lapply(folds, function(x) {
  training_fold <- shop_train[-x,]
  test_fold <- shop_train[x,]
  
  clf <- C5.0(Revenue ~ .,
              data = training_fold)
  
  y_pred <- predict(clf, newdata = test_fold[,-index])
  cm = table(test_fold$Revenue, y_pred)
  balanced_accuracy <- 0.5*(cm[1,1]/(cm[1,1]+cm[1,2]) + cm[2,2]/(cm[2,2]+cm[2,1]))
  return(balanced_accuracy)
})
dt1_bac <- mean(as.numeric(dt_cv1))
dt1_bac


dt_cv2 = lapply(folds, function(x) {
  training_fold <- shop_train[-x,]
  test_fold <- shop_train[x,]
  
  error_cost <- matrix(c(0, 1, 4, 0), nrow = 2)
  
  clf <- C5.0(Revenue ~ .,
              data = training_fold,
              costs = error_cost)
  
  y_pred <- predict(clf, newdata = test_fold[,-index])
  cm = table(test_fold$Revenue, y_pred)
  balanced_accuracy <- 0.5*(cm[1,1]/(cm[1,1]+cm[1,2]) + cm[2,2]/(cm[2,2]+cm[2,1]))
  return(balanced_accuracy)
})
dt2_bac <- mean(as.numeric(dt_cv2))
dt2_bac
```











