---
title: "Data Visualization"
author: "Samuel Bugaieski"
date: "4/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Data Prep}
shopping <- read.csv("online_shoppers_intention.csv")
str(shopping)

#converting weekend and revenue variables into a numeric value
shopping$WeekendD <- as.numeric(shopping$Weekend)
shopping$RevenueD <- as.numeric(shopping$Revenue)
shopping$Weekend <- shopping$WeekendD
shopping$Revenue <- shopping$RevenueD
shopping$WeekendD <- NULL
shopping$RevenueD <- NULL

#Dividing variables by their Dependent Variable
success <- shopping[shopping$Revenue == 1,]
fail <- shopping[shopping$Revenue == 0,]

#Creating numeric variable for Month
shopping$MonthN <- 1

shopping[shopping$Month == "Feb",]$MonthN <- 2
shopping[shopping$Month == "Mar",]$MonthN <- 3
shopping[shopping$Month == "May",]$MonthN <- 5
shopping[shopping$Month == "June",]$MonthN <- 6
shopping[shopping$Month == "Jul",]$MonthN <- 7
shopping[shopping$Month == "Aug",]$MonthN <- 8
shopping[shopping$Month == "Sep",]$MonthN <- 9
shopping[shopping$Month == "Oct",]$MonthN <- 10
shopping[shopping$Month == "Nov",]$MonthN <- 11
shopping[shopping$Month == "Dec",]$MonthN <- 12

```

#Comparison of results with respect to time

```{r}
#Not sure if this is valuable from the standpoint of creating a model, but evaluating effect of timeframes on sales conversion

barplot(tapply(shopping$Revenue, shopping$MonthN, mean))
#Customers significantly more likely to purchase between months of July and November

#^with GGPlot as stacked bar with total count (also not sure if density graph is helpful here):
MonthDensity <- ggplot(data = shopping, aes(x = MonthN, colour = colrange))
MonthDensity + geom_bar()
MonthDensity + geom_density()

barplot(tapply(shopping$Revenue, shopping$Weekend, mean), ylim = c(0,.3))
#Customers marginally more likely to purchase on weekends

#^with GGPlot as stacked bar with total count:
WeekendDensity <- ggplot(data = shopping, aes(x = Weekend, colour = colrange))
WeekendDensity + geom_bar()

barplot(tapply(shopping$Revenue, shopping$SpecialDay, mean))
#May have done something wrong here but this seems to suggest a counterintuitive trend towards buying around special days

#^with GGPlot as stacked bar with total count:
SDDensity <- ggplot(data = shopping, aes(x = SpecialDay, colour = colrange))
SDDensity + geom_bar()

```

#Exploring impact of region on purchase
```{r}
barplot(tapply(shopping$Revenue, shopping$Region, mean), ylim = c(0,.2))
#Region does not seem to be overly significant in impacting sales conversion

```

#Exploring impact of customer experience metrics
```{r}
barplot(tapply(shopping$Revenue, shopping$OperatingSystems, mean), ylim = c(0,.25))
#Names are not included in dataframe or attached guide - OS 8 has the highest sales conversion by a small margin and OS 3 and 6 are notably lower than the average

barplot(tapply(shopping$Revenue, shopping$Browser, mean))
#Names are not included in dataframe or attached guide - Browsers 12 and 13 have the highest sales conversion by a decent margin and Browsers 3 and 6 are notably lower than the average

barplot(tapply(shopping$Revenue, shopping$TrafficType, mean))
#Names are not included in dataframe or attached guide - Significant difference in sales turnover across different types of traffic.

barplot(tapply(shopping$Revenue, shopping$VisitorType, mean), ylim = c(0,.25))
#New visitors seem the most likely to purchase, Returning visitors are least likely

```

#Changing my approach testing for interactions now

```{r}
library(ggplot2)

colrange <- ifelse(shopping$Revenue == 1, "Purchase", "No Purchase")

#Testing relationship between Administrative and Informational page visits and duration

Admin_vs_Inf <- ggplot(data = shopping, aes(x = Administrative, y = Informational, colour = colrange))  + geom_jitter(alpha = 0.5)
Admin_vs_Inf + geom_point()
#Added Jitter because there was a lot of overlap

Admin_vs_Inf_Duration <- ggplot(data = shopping, aes(x = Administrative_Duration, y = Informational_Duration, colour = colrange))
Admin_vs_Inf_Duration + geom_point()

#Testing relationship between Informational and Product page visits and duration

Inf_vs_Prod <- ggplot(data = shopping, aes(x = Informational, y = ProductRelated, colour = colrange)) + geom_jitter(alpha = 0.5)
Inf_vs_Prod + geom_point()
#Added Jitter because there was a lot of overlap

Inf_vs_Prod_Duration <- ggplot(data = shopping, aes(x = Informational_Duration, y = ProductRelated_Duration, colour = colrange))
Inf_vs_Prod_Duration + geom_point()

#Testing relationship between Product and Administrative page visits and duration

Prod_vs_Admin <- ggplot(data = shopping, aes(x = ProductRelated, y = Administrative, colour = colrange)) + geom_jitter(alpha = 0.5)
Prod_vs_Admin + geom_point()
#Added Jitter because there was a lot of overlap

Prod_vs_Admin_Duration <- ggplot(data = shopping, aes(x = ProductRelated_Duration, y = Administrative_Duration, colour = colrange))
Prod_vs_Admin_Duration + geom_point()

#Testing relationship between Bounce Rate and Exit Rate

Bounce_vs_Exit <- ggplot(data = shopping, aes(x = BounceRates, y = ExitRates, colour = colrange))
Bounce_vs_Exit + geom_point()

```







