---
title: "naman trying knn"
author: "Naman Gupta"
date: "4/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# tune on only the new train set, dont touch new test set
```{r}
library(class)
library(gmodels)
library(caret)
library(C50)
library(irr)
library(ROCR)
library(ipred)
library(randomForest)
```

```{r}
# Set the same seed
set.seed(123)
df <- read.csv("online_shoppers_intention.csv")

rows <- sample(nrow(df))
shopping <- df[rows,]

shopping$WeekendD <- as.numeric(shopping$Weekend)
shopping$RevenueD <- as.numeric(shopping$Revenue)
shopping$Weekend <- shopping$WeekendD
shopping$Revenue <- as.factor(shopping$RevenueD)
shopping$WeekendD <- NULL
shopping$RevenueD <- NULL

shopping$NewVisitor <- ifelse(shopping$VisitorType == "New_Visitor",1,0)
shopping$VisitorType <- NULL
shopping$HolidaySeason <- ifelse(shopping$Month == "Oct" | shopping$Month == "Nov" | shopping$Month == "Dec",1,0)
shopping$Month <- NULL
summary(shopping)
shopping_use <- shopping

normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

shopping_n <- as.data.frame(lapply(shopping[-16], normalize)) #started at column 2, because no point in normalizing the binary "outcome"
shopping_n$Revenue <- shopping$Revenue

# This is roughly a 70/30 train/test split
# Only use the train data to tune and improve models right now
shopping_use <- shopping_n[1:8630,]
shopping_test_DNU <- shopping_n[8631:12330,]
```

```{r}
shopping_use_train <- shopping_use[1:7000, ] #keep rest rows for train
shopping_use_test <- shopping_use[7001:nrow(shopping_use), ] #keep 100 rows for test

shopping_use_train_labels <- shopping_use[1:7000, 16]
shopping_use_test_labels <- shopping_use[7001:nrow(shopping_use), 16]


shopping_test_pred <- knn(train = shopping_use_train, test = shopping_use_test,
                      cl = shopping_use_train_labels, k=7)

CrossTable(x = shopping_use_test_labels, y = shopping_use_test_pred, 
           prop.chisq=FALSE)

confusionMatrix(shopping_use_test_pred, shopping_use_test_labels, positive = "1")


trControl <- trainControl(method  = "cv",
                          number  = 5)

fit <- train(Revenue ~ .,
             method     = "knn",
             tuneGrid   = expand.grid(k = 1:10),
             trControl  = trControl,
             metric     = "Accuracy",
             data       = shopping_use)

fit

trControl <- trainControl(method  = "cv",
                          number  = 10)

fit <- train(Revenue ~ .,
             method     = "knn",
             tuneGrid   = expand.grid(k = 1:10),
             trControl  = trControl,
             metric     = "Accuracy",
             data       = shopping_use)

fit
```

#no need to use rest of these, i think
```{r}
shopping_train <- shopping_n[1:8630, ] #keep rest rows for train
shopping_test <- shopping_n[8631:nrow(shopping_n), ] #keep 100 rows for test
shopping_train_labels <- shopping_use[1:8630, 16]
shopping_test_labels <- shopping[8631:nrow(shopping_n), 16]

shopping_test_pred <- knn(train = shopping_train, test = shopping_test,
                      cl = shopping_train_labels, k=1)

CrossTable(x = shopping_test_labels, y = shopping_test_pred, 
           prop.chisq=FALSE)

confusionMatrix(shopping_test_pred, shopping_test_labels, positive = "1")

shopping_test_pred <- knn(train = shopping_train, test = shopping_test,
                      cl = shopping_train_labels, k=11)

CrossTable(x = shopping_test_labels, y = shopping_test_pred, 
           prop.chisq=FALSE)

confusionMatrix(shopping_test_pred, shopping_test_labels, positive = "1")

shopping_test_pred <- knn(train = shopping_train, test = shopping_test,
                      cl = shopping_train_labels, k=31)

CrossTable(x = shopping_test_labels, y = shopping_test_pred, 
           prop.chisq=FALSE)

confusionMatrix(shopping_test_pred, shopping_test_labels, positive = "1")

shopping_test_pred <- knn(train = shopping_train, test = shopping_test,
                      cl = shopping_train_labels, k=51)

CrossTable(x = shopping_test_labels, y = shopping_test_pred, 
           prop.chisq=FALSE)

confusionMatrix(shopping_test_pred, shopping_test_labels, positive = "1")

shopping_test_pred <- knn(train = shopping_train, test = shopping_test,
                      cl = shopping_train_labels, k=101)

CrossTable(x = shopping_test_labels, y = shopping_test_pred, 
           prop.chisq=FALSE)

confusionMatrix(shopping_test_pred, shopping_test_labels, positive = "1")

shopping_test_pred <- knn(train = shopping_train, test = shopping_test,
                      cl = shopping_train_labels, k=sqrt(nrow(shopping)))

CrossTable(x = shopping_test_labels, y = shopping_test_pred, 
           prop.chisq=FALSE)

confusionMatrix(shopping_test_pred, shopping_test_labels, positive = "1")

shopping_test_pred <- knn(train = shopping_train, test = shopping_test,
                      cl = shopping_train_labels, k=151)

CrossTable(x = shopping_test_labels, y = shopping_test_pred, 
           prop.chisq=FALSE)

confusionMatrix(shopping_test_pred, shopping_test_labels, positive = "1")
```


